version: "3.0"

services:
  cloudflare-warp-proxy:
    image: seiry/cloudflare-warp-proxy
    network_mode: bridge
    ports:
      - 40000:40000
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
